apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: jkube-demo-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/rohanKanojia/eclipse-jkube-demo-project